# -*- coding: utf-8 -*-
"""87952-BOOTCAMP-CLASE-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RboXowTBsRVwqafhPspPew8wEWsCJXo

# Mis primeros pasos con Python
"""

print("¡Bienvenidos al programa saludador!")

nombre = input("Dime tu nombre y te saludo: ")
print(f"Bienvenido {nombre}")

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Generate date range for the last 2 years up to mid-2026
dates = pd.date_range(start='2024-01-01', end='2026-08-01', freq='B')

# Generate realistic stock price trajectories
# MSFT starting around $370, growing steadily
msft_returns = np.random.normal(0.0005, 0.012, len(dates))
msft_prices = 370 * np.exp(np.cumsum(msft_returns))

# NVDA starting around $48 (split-adjusted), with high volatility and strong growth
nvda_returns = np.random.normal(0.0018, 0.025, len(dates))
nvda_prices = 48 * np.exp(np.cumsum(nvda_returns))

# Create DataFrame
df = pd.DataFrame({
    'Date': dates,
    'Microsoft (MSFT)': msft_prices,
    'NVIDIA (NVDA)': nvda_prices
}).set_index('Date')

# Plotting
plt.figure(figsize=(12, 6))
plt.plot(df.index, df['Microsoft (MSFT)'], label='Microsoft (MSFT)', color='#00A4EF', linewidth=2)
plt.plot(df.index, df['NVIDIA (NVDA)'], label='NVIDIA (NVDA)', color='#76B900', linewidth=2)

# Formatting
plt.title('Cotización Historica Estimada: NVIDIA (NVDA) vs. Microsoft (MSFT)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Precio por Acción (USD)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(fontsize=12, loc='upper left')
plt.tight_layout()

# Save image
plt.savefig('nvidia_vs_msft.png', dpi=300)
plt.show()